// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdjtjsclvdrmwaxhaiaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkanRqc2NsdmRybXdheGhhaWFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1OTY3NjQsImV4cCI6MjA3MDE3Mjc2NH0._ithJp6DEuCC9P9Z8fADerkKqcPonQrgytN9iPl0IXA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});